.TH FREEVIAL "6" "November 24, 2007" "Freevial Gresca"

.SH NAME
freevial \- trivia platform for community events

.SH SYNOPSIS
.B freevial
[\fIOPTIONS\fR] [\-\-database <PATH>] [\-\-skin <PATH>]

.SH DESCRIPTION
This page briefly documents the \fBfreevial\fR command. Freevial is
trivia-like game for community events (idealy to be played with a
projector).

.SH USAGE
You may need to specify the path to the questions database you want to
use with the \-\-database argument. The database can be either folder
or a compressed file.
.PP
Additionaly, you can choose a different look using the \-\-skin option
to tell it where the appearance information it should use is located.

.SH OPTIONS
.TP
.B \-d, \-\-debug
Run Freevial in debug mode (this doesn't change much at all).
.TP
.B \-m, \-\-mute
Disable music and sounds.
.TP
.B \-f, \-\-fullscreen
Start in fullscreen mode (it can be windowed ingame with F11).
.TP
.B \-l, \-\-locked
Start in locked mode (game can't be closed nor questions aborted; unlock by pressing the
l-key in the team selection screen).
.TP
.B \-h, \-\-help
Prints the help and exists.
.TP
.B \-v, \-\-version
Prints information about the current version and release series, and exists.
.TP
.B \-\-info\-db, \-\-info\-database
Prints information about the loaded database and exists. This can be combined
with the \-\-database option.
.TP
.B \-\-no\-sound
Disables all sounds. You can use \-\-mute to also disable the music.
.TP
.B \-\-no\-music
Disables the music. You can use \-\-mute to also disable sounds.
.TP
.B \-\-fps
Displays the framerate on screen.
.TP
.B \-\-psyco
Tries to use the psyco module in order to accelerate Freevial. This is
not recommended, as it will need more memory.

.SH FILES
.TP
.I ~/.config/freevial/preferences.ini
Per user configuration file.

.SH REPORTING BUGS
If you find any bug please report it on: https://bugs.launchpad.net/freevial/.

.SH AUTHOR
Freevial was written by Carles Oriol <carles@kumbaworld.com> and
Siegfried-Angel Gevatter Pujals <siggi.gevatter@gmail.com>.

.SH COPYRIGHT
Copyright \(co 2007-2009 The Freevial Team
.PP
Freevial is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License, either version 3 of
the License or any later version.
.PP
Freevial is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; see the GNU General Public License for more details.
