#! /usr/bin/env python
# -*- coding: utf-8 -*-

#
# Freevial
# Game Launcher
#
# Copyright (C) 2007-2009 The Freevial Team
#
# By Carles Oriol i Margarit <carles@kumbaworld.com>
# By Siegfried-Angel Gevatter Pujals <siggi.gevatter@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import sys
import os

cwd = os.path.dirname(os.path.abspath(__file__))

def find_dir(*directories):

	for directory in directories:
		if os.path.exists(os.path.join(directory, 'freevial.py')):
			return directory
	
	return None

directory = find_dir(os.path.join(cwd, 'src'), '/usr/share/games/freevial/src',
	'/usr/share/freevial/src', '/opt/freevial/src')

if not directory:
	print >> sys.stderr, "Couldn't determine the path to any existing Freevial installation."
	sys.exit(1)

# Pass Freevial the path from where it's really called
sys.argv.extend(('--real', os.getcwd()))

os.chdir(directory)
sys.path.insert(0, directory)

# Start game
try:
	import freevial
except KeyboardInterrupt:
	print 'User requested interrupt.'
	sys.exit(0)
