#! /usr/bin/env python2.5
# -*- coding: utf-8 -*-

#
# Freevial
# Game Launcher
#
# Copyright (C) 2007 The Freevial Team
#
# By Carles Oriol i Margarit <carles@kumbaworld.com>
# By Siegfried-Angel Gevatter Pujals <siggi.gevatter@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import os, sys

directory = os.path.dirname(os.path.abspath(__file__))

def isdir(path, addpath = ''):
	return os.path.exists(os.path.join(path, addpath, 'freevial.py'))

if not isdir(directory):
	if isdir(directory, 'src'):
		directory = os.path.join(directory, 'src')
	else:
		directory = '/usr/share/games/freevial/src'
		if not isdir(directory):
			print "Couldn't determine the path to any existing Freevial installation."
			sys.exit(1)

os.chdir(directory)
sys.path.insert(0, directory)

# Start game
import freevial
